name: dependabot-auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - id: meta
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: auto-merge gomod patch
        if: >-
          steps.meta.outputs.package-ecosystem == 'gomod' &&
          steps.meta.outputs.update-type == 'version-update:semver-patch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge "${{ github.event.pull_request.html_url }}" --squash --auto

      - name: auto-merge github-actions non-major
        if: >-
          steps.meta.outputs.package-ecosystem == 'github-actions' &&
          steps.meta.outputs.update-type != 'version-update:semver-major'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge "${{ github.event.pull_request.html_url }}" --squash --auto
